Home page
Mihndim2020/Positioning-and-floating-elements pull request #1
Opened 2021-01-12 20:18 UTC by Mihndim2020

2021-01-14 19:53 UTC, abredi requested changes
### Status: Require changes 🌳 ♲
Hi @Mihndim2020 and @promise-J, I am Abdulaziz Redi Ali, your TSE for this PR.  👏👏  I appreciate your hard work in replicating nytimes.com.   Kindly fix the following issues.

[REQUIRED]

- [x] Fix web hint linting errors
- [x] Add buttons to the right-most part of the navigation bar
- [ ] Align all elements in the page to the center

 
| Your Copy | Original | 
| :---:         |     :---:      |
|![alignment_copy](https://user-images.githubusercontent.com/38358081/104640590-bb862000-56b9-11eb-811d-6f0062b10d0e.png)  | ![alignment_original](https://user-images.githubusercontent.com/38358081/104640646-ce98f000-56b9-11eb-8b95-1a2f6319946b.png) |
|![alignment2_copy](https://user-images.githubusercontent.com/38358081/104640684-dbb5df00-56b9-11eb-914e-d370cce95abd.png) |![alignment2_original](https://user-images.githubusercontent.com/38358081/104640796-00aa5200-56ba-11eb-96c3-9092f40c1fb7.png) |

- [ ] The page shouldn't scroll horizontally fix the overflow and horizontal scrolling.
![horizontal_scrolling](https://user-images.githubusercontent.com/38358081/104641204-84fcd500-56ba-11eb-93cf-5788664ac03a.png)
- [ ] Fix the alignment and styling of Editors Pick's section to look more like the original page

| Your Copy | Original | 
| :---:         |     :---:      |
|![editors_pick_copy](https://user-images.githubusercontent.com/38358081/104641308-a5c52a80-56ba-11eb-9a12-c70f563fb9eb.png) |![editors_pick_original](https://user-images.githubusercontent.com/38358081/104641449-d3aa6f00-56ba-11eb-9e09-5d939fefdf4b.png) |

- [ ] The articles in the "Most popular"  and the "suggested articles" section in the bottom part of the page should be links

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2021-01-14 19:53 UTC, abredi requested changes
### Status: Require changes 🌳 ♲
Hi @Mihndim2020 and @promise-J, I am Abdulaziz Redi Ali, your TSE for this PR.  👏👏  I appreciate your hard work in replicating nytimes.com.   Kindly fix the following issues.

[REQUIRED]

- [ ] Fix web hint linting errors
- [ ] Add buttons to the right-most part of the navigation bar
- [ ] Align all elements in the page to the center

 
| Your Copy | Original | 
| :---:         |     :---:      |
|![alignment_copy](https://user-images.githubusercontent.com/38358081/104640590-bb862000-56b9-11eb-811d-6f0062b10d0e.png)  | ![alignment_original](https://user-images.githubusercontent.com/38358081/104640646-ce98f000-56b9-11eb-8b95-1a2f6319946b.png) |
|![alignment2_copy](https://user-images.githubusercontent.com/38358081/104640684-dbb5df00-56b9-11eb-914e-d370cce95abd.png) |![alignment2_original](https://user-images.githubusercontent.com/38358081/104640796-00aa5200-56ba-11eb-96c3-9092f40c1fb7.png) |

- [ ] The page shouldn't scroll horizontally fix the overflow and horizontal scrolling.
![horizontal_scrolling](https://user-images.githubusercontent.com/38358081/104641204-84fcd500-56ba-11eb-93cf-5788664ac03a.png)
- [ ] Fix the alignment and styling of Editors Pick's section to look more like the original page

| Your Copy | Original | 
| :---:         |     :---:      |
|![editors_pick_copy](https://user-images.githubusercontent.com/38358081/104641308-a5c52a80-56ba-11eb-9a12-c70f563fb9eb.png) |![editors_pick_original](https://user-images.githubusercontent.com/38358081/104641449-d3aa6f00-56ba-11eb-9e09-5d939fefdf4b.png) |

- [ ] The articles in the "Most popular"  and the "suggested articles" section in the bottom part of the page should be links

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2021-01-15 02:03 UTC, ElijahTobs requested changes
# Status: Changes Required :recycle: 

## Hi @Mihndim2020 :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this project can be approved.

## REQUIRED

* [ ] Please, make all the changes as requested by the previous TSE.
* [ ] Please, work on this:
**Yours**
![image](https://user-images.githubusercontent.com/16058470/104670945-18df9880-56dd-11eb-9841-34c13ea1ed5a.png)
**Original**
![image](https://user-images.githubusercontent.com/16058470/104671026-42002900-56dd-11eb-9527-0c3f3ae39519.png)
- [ ] Kindly make sure your page looks exactly like the [original](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)

### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2021-01-15 02:24 UTC, ioilmio requested changes
Hello @Mihndim2020 @promise-J  👋🏽 
Nice job till now let's improve it 🦾 
Required changes 🔴 :

### Header section

- #### What happened to the bookmark icon? Please fix it

### Caption 

- #### Please align the caption correctly, for the big image;

### Theory of inflation 

- #### You are almost there, but some text is still overlapped, please fix it;

### Video
-  #### Should be centered along with its caption;

### Last image
- #### Caption and text form the paragraph are mixed please fix them;

### Footer 
- Editor's pick section is not as the original, please fix it;


# General
## Add node_modules folder to your .gitignore file, so it won't be pushed ot github;
## Fix your readme layout;
## Text in the page should be in the center, not jutified to center;

# For further info contact me on slack @illuminatosalvatore 

Happy coding 💻

2021-01-15 02:24 UTC, ioilmio commented on index.html
> +        <!-- the social section of the pages -->
Remove comments

2021-01-15 02:24 UTC, ioilmio commented on index.html
> +            <!-- a child content that makes styling the inner contents much easier -->
Remove comments

2021-01-15 02:24 UTC, ioilmio commented on index.html
> +        <!-- the section about CAMBRIDGE with a date stamp...the long text -->
Remove comments

2021-01-16 03:28 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Jp Johnson Alisigwe** 
Good job with the improvements for this project :muscle:  :muscle:
Your page looks like the original :clap: :clap: :clap:  
There are just a few details to correct before you can go ahead:

- [ ] Add  screenshot in your README file
- [ ] Add a link to the Live Demo of your page
- [ ] The website logo, in the top navbar, should be a link
- [ ] "SPACE AND COSMOS" text, in the top navbar, should be a link
- [ ] In your CSS file, group selectors with the same style definition
- [ ] Your project should align elements with a combination of all three techniques (float, flex and grid). 
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-01-16 13:01 UTC, promise-J commented
Hello Oscar, we have done the changes as requested in your review above.
please could you get back to us on the project? thank you
https://github.com/Mihndim2020/Positioning-and-floating-elements/pull/1

On Fri, Jan 15, 2021 at 3:28 PM Oscar Andrés Russi Porras <
notifications@github.com> wrote:

> *@andresporras3423* requested changes on this pull request.
> Status: Changes Required ♻️
>
> *Hello Jp Johnson Alisigwe*
> Good job with the improvements for this project 💪 💪
> Your page looks like the original 👏 👏 👏
> There are just a few details to correct before you can go ahead:
>
>    - Add screenshot in your README file
>    - Add a link to the Live Demo of your page
>    - The website logo, in the top navbar, should be a link
>    - "SPACE AND COSMOS" text, in the top navbar, should be a link
>    - Group selectors with the same style definition
>    - Your project should align elements with a combination of all three
>    techniques (float, flex and grid).
>
> Please request another review once you are ready! 👍
>
> Happy coding ☺️
>
> Oscar Andrés Russi Porras
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Mihndim2020/Positioning-and-floating-elements/pull/1#pullrequestreview-569808214>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANXPBMFNCEAX7ENJIG6JOLDS2EBWVANCNFSM4V7X3AFA>
> .
>

2021-01-16 21:18 UTC, eypsrcnuygr requested changes
## Status: Changes Required :recycle: 
Hello team. Your page looks good but there are some things that need to be solved before moving on. :smile: 

![1](https://user-images.githubusercontent.com/33910796/104823099-9976d400-5858-11eb-804a-61b480f076f1.png)

- [ ]  Please align those social icons and give a bit of padding to them.

![2](https://user-images.githubusercontent.com/33910796/104823109-ac89a400-5858-11eb-9e05-53f097b9bf40.png)

- [ ]  Please align the sentence as on the original page.

![3](https://user-images.githubusercontent.com/33910796/104823115-bca18380-5858-11eb-92cd-7ede8ecfed9b.png)

- [ ]  Please place the editor's section a bit more to left.

![4](https://user-images.githubusercontent.com/33910796/104823129-d5aa3480-5858-11eb-978f-ccdd4d546d2c.png)

- [ ]  Please align this image on the center. 

![5](https://user-images.githubusercontent.com/33910796/104823136-e6f34100-5858-11eb-9f49-9627d6d86de8.png)

- [ ]  There is an overlapping issue as you can see from the screenshot above. Kindly fix this issue.
- [ ] On your readme, put the license as a link, don't copy and paste all the license.

### Optional

- [ ]  You can work on the footer, decrease the size of it, and make it as on the original page.

Again, a good start and don't be discouraged from the reviews. It is to help you improve your skills. :+1: 

Please fix those mentioned issues and submit for a re-review after that.
If you have any questions about the review, feel free to reach out to me via Slack. :100: 
_Eyüp Sercan UYGUR_

2021-01-16 21:28 UTC, abredi requested changes
### Status: Require changes 🌳 ♲
Hi @Mihndim2020 and @promise-J , I am Abdulaziz Redi Ali, your TSE for this PR.  👏👏  I appreciate your hard work in replicating nytimes.com.   Kindly fix the following issues.

[REQUIRED]

1. - [ ] The editor's pick section should be before the "The Theory of Inflation".
2. - [ ] Implement the footer action button for the main article
3. - [ ] Fix the footer, it should have a similar font style to the original.

 
| # | Your Copy | Original | 
| :---:| :---:         |     :---:      |
| 1 | ![IMAGE 2021-01-16 13:21:07](https://user-images.githubusercontent.com/38358081/104823252-b205d080-57fd-11eb-88bc-f220f56ae5bf.jpg)|![Screenshot 2021-01-16 235622](https://user-images.githubusercontent.com/38358081/104823238-98648900-57fd-11eb-8390-2e4e3528753d.png)| 
| 2 | <img width="888" alt="Screen Shot 2021-01-16 at 1 22 58 PM" src="https://user-images.githubusercontent.com/38358081/104823283-f6916c00-57fd-11eb-95b5-fa5a0f1d706e.png"> | <img width="819" alt="Screen Shot 2021-01-16 at 1 01 12 PM" src="https://user-images.githubusercontent.com/38358081/104823353-6bfd3c80-57fe-11eb-942b-d715598217df.png"> |
| 3 | <img width="1133" alt="Screen Shot 2021-01-16 at 1 23 34 PM" src="https://user-images.githubusercontent.com/38358081/104823292-0b6dff80-57fe-11eb-83b6-3b5e00a76892.png">|<img width="1470" alt="Screen Shot 2021-01-16 at 1 24 01 PM" src="https://user-images.githubusercontent.com/38358081/104823310-23de1a00-57fe-11eb-9032-3bcbad9abf91.png"> |

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2021-01-18 19:17 UTC, mimipeshy commented
### STATUS : CHANGES REQUIRED :red_circle: :recycle: 

Hello @Mihndim2020 This is good to make it this far, your project is really nice, congratulations on the good work you have done so far. I liked that you have implemented the requested changes from the previous review, keep it up, and your project is really almost done. One change is required:

- [ ] Your README file format is distorted. You have entered the same information twice. Kindly check on it.
- [ ] The getting started section should contain instructions on how to set up your project locally. Kindly add them.

That's all :smile: , kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, I will be glad to help_
Regards
Peris Ndanu

2021-01-18 20:03 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello `Jp Johnson Alisigwe` :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] You need to add a description to this Pull Request
- [ ] Files not related to the project should not be committed and added to .gitignore (e.g. `node_modules`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] You need to fix your readme file, the `author` and `license` sections are duplicated (present twice), fix them
- [ ] The bottom part of your clone, before the footer, the text is overlapping pictures, fix that.
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-01-18 20:08 UTC, promise-J commented
[image: g1.PNG][image: g2.PNG][image: f1.PNG][image: f2.PNG]

On Mon, Jan 18, 2021 at 8:03 AM Mugirase Emmanuel <notifications@github.com>
wrote:

> *@descholar-ceo* requested changes on this pull request.
> Status: Changes Required 🚦 ⚠️ Hello Jp Johnson Alisigwe 🤝 🤝 🤝
>
> 👍 This is good to make it this far, your clone looks like the original
> page and it is really nice, congratulations on the good work you have done
> so far.
> 👍 I liked that you have tried to implemented the requested changes from
> the previous review, keep it up, and your project is really almost done.
> ⚠️ However we need to make few changes to mark this project approved,
> don't feel discouraged because of being asked some changes more and more,
> that's beacuse this is a learning process, and we are here to help you to
> become an out-standing developer. See the requested change below 👇 👇 👇 Note:
> All of requested changes which are marked as [Required] are mandatory to be
> implemented in order to get this project approved, others which are marked
> as [Optional] are nice to have in your project to make it outstanding [Required
> Changes] 🔴
>
>    - You need to add a description to this Pull Request
>    - Files not related to the project should not be committed and added
>    to .gitignore (e.g. node_modules) (screenshot
>    <https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png>
>    from Pathwright
>    <https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/>
>    )
>    - You need to fix your readme file, the author and license sections
>    are duplicated (present twice), fix them
>    - The bottom part of your clone, before the footer, the text is
>    overlapping pictures, fix that.
>
> ------------------------------
>
> *If anything seems to be unclear to you, reachout and ask anything by
> commenting on this Pull Request and mention me as descholar-ceo
> <https://github.com/descholar-ceo>, I will receive a notification and will
> respond.*
>
> GitHub <https://github.com/descholar-ceo> | LinkedIn
> <https://linkedin.com/in/mugirase-emmanuel> | Twitter
> <https://twitter.com/descholar3>
>
> *Reviewed by Mugirase Emmanuel (descholar)
> <https://github.com/descholar-ceo>*
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Mihndim2020/Positioning-and-floating-elements/pull/1#pullrequestreview-570752666>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANXPBMDRDF27CNEG5SPO2YLS2SHZ5ANCNFSM4V7X3AFA>
> .
>

2021-01-18 20:09 UTC, promise-J commented
this is my view on the browser. both on chrome and on Mozilla fire fox. the
are both responsive.

On Mon, Jan 18, 2021 at 8:08 AM Johnson Promise <chiemelapromise30@gmail.com>
wrote:

> [image: g1.PNG][image: g2.PNG][image: f1.PNG][image: f2.PNG]
>
> On Mon, Jan 18, 2021 at 8:03 AM Mugirase Emmanuel <
> notifications@github.com> wrote:
>
>> *@descholar-ceo* requested changes on this pull request.
>> Status: Changes Required 🚦 ⚠️ Hello Jp Johnson Alisigwe 🤝 🤝 🤝
>>
>> 👍 This is good to make it this far, your clone looks like the original
>> page and it is really nice, congratulations on the good work you have done
>> so far.
>> 👍 I liked that you have tried to implemented the requested changes from
>> the previous review, keep it up, and your project is really almost done.
>> ⚠️ However we need to make few changes to mark this project approved,
>> don't feel discouraged because of being asked some changes more and more,
>> that's beacuse this is a learning process, and we are here to help you to
>> become an out-standing developer. See the requested change below 👇 👇 👇 Note:
>> All of requested changes which are marked as [Required] are mandatory to be
>> implemented in order to get this project approved, others which are marked
>> as [Optional] are nice to have in your project to make it outstanding [Required
>> Changes] 🔴
>>
>>    - You need to add a description to this Pull Request
>>    - Files not related to the project should not be committed and added
>>    to .gitignore (e.g. node_modules) (screenshot
>>    <https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png>
>>    from Pathwright
>>    <https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/>
>>    )
>>    - You need to fix your readme file, the author and license sections
>>    are duplicated (present twice), fix them
>>    - The bottom part of your clone, before the footer, the text is
>>    overlapping pictures, fix that.
>>
>> ------------------------------
>>
>> *If anything seems to be unclear to you, reachout and ask anything by
>> commenting on this Pull Request and mention me as descholar-ceo
>> <https://github.com/descholar-ceo>, I will receive a notification and will
>> respond.*
>>
>> GitHub <https://github.com/descholar-ceo> | LinkedIn
>> <https://linkedin.com/in/mugirase-emmanuel> | Twitter
>> <https://twitter.com/descholar3>
>>
>> *Reviewed by Mugirase Emmanuel (descholar)
>> <https://github.com/descholar-ceo>*
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Mihndim2020/Positioning-and-floating-elements/pull/1#pullrequestreview-570752666>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ANXPBMDRDF27CNEG5SPO2YLS2SHZ5ANCNFSM4V7X3AFA>
>> .
>>
>

2021-01-18 20:24 UTC, promise-J commented
![g1](https://user-images.githubusercontent.com/57602224/104959809-61f64d80-5966-11eb-8988-30a860f938f5.PNG)
![g2](https://user-images.githubusercontent.com/57602224/104959830-6884c500-5966-11eb-82eb-07a3ced3d71f.PNG)
![f1](https://user-images.githubusercontent.com/57602224/104959857-75091d80-5966-11eb-8920-3867d1373aac.PNG)
![m2](https://user-images.githubusercontent.com/57602224/104959864-78040e00-5966-11eb-8e35-8a8c550aef6c.PNG)


these are the views on Mozilla and chrome for the specified sections.

2021-01-18 20:37 UTC, promise-J commented
Fixed the redundancy in the README file.

2021-01-18 20:51 UTC, promise-J commented
I added all files not related to the project to .gitignore (e.g. node_modules)
I fixed the readme file, the author and license sections that appeared twice was erased.
 Fixed the overlapping text in the footer.

2021-01-18 22:53 UTC, Temmarie approved these changes
## Status: Approved :heavy_check_mark:

### Hi @Mihndim2020 and @promise-J  ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

 **Optional**
- [ ] Use [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) chrome extension to help with the varying font-sizes and family required.

#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2021-01-18 23:28 UTC, merged